import React from 'react'
import Head from 'next/head'
import App from '@/components/app/app'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App Update</title>
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta name="subject" content="" />
        <meta name="copyright" content="" />
        <meta name="robots" content="index,follow" />
        <meta name="Classification" content="" />
        <meta name="author" content="" />
        <meta name="url" content="" />
        <meta name="identifier-URL" content="" />
        <meta name="coverage" content="Worldwide" />
        <meta name="distribution" content="Global" />
        <meta name="rating" content="General" />
        <meta name="revisit-after" content="7 days" />
        <meta httpEquiv="Expires" content="0" />
        <meta httpEquiv="Pragma" content="no-cache" />
        <meta httpEquiv="Cache-Control" content="no-cache" />
      </Head>
      <main>
        <App />
      </main>
    </>
  )
}
